# Generated by Django 2.0.4 on 2018-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('actor_name', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=200)),
                ('watched', models.BooleanField(default=False)),
                ('date_released', models.DateTimeField()),
            ],
        ),
    ]
