<<<<<<< HEAD
# Generated by Django 2.0.4 on 2018-05-01 14:32
=======
# Generated by Django 2.0.4 on 2018-04-25 20:00
>>>>>>> 3e978d94bd540b321e23aae828bae26654f88ae8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
=======
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('actor_name', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=200)),
                ('watched', models.BooleanField(default=False)),
                ('date_released', models.DateTimeField()),
>>>>>>> 3e978d94bd540b321e23aae828bae26654f88ae8
            ],
        ),
    ]
