# Generated by Django 2.0.4 on 2018-05-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_wishlist', '0003_watchedlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='title',
            new_name='name',
        ),
    ]
