# Generated by Django 2.0.4 on 2018-05-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_wishlist', '0004_auto_20180503_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
