# Generated by Django 2.0.4 on 2018-05-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_wishlist', '0006_auto_20180506_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedlist',
            name='rating',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
